### ISSUE TITLE
yo this got flagged in MalwareBytes

### ISSUE THREAD

**Issue by sohamdata** [seanfhear/tab-scraper#21]
![image](https://user-images.githubusercontent.com/78294692/154627737-46dad91d-6c67-4134-9df1-5e6a40842413.png)

log: 
-Scan Details-
Process: 0
(No malicious items detected)

Module: 0
(No malicious items detected)

Registry Key: 0
(No malicious items detected)

**Registry Value: 2
PUM.Optional.DisableMRT, HKLM\SOFTWARE\WOW6432NODE\POLICIES\MICROSOFT\MRT|DONTREPORTINFECTIONINFORMATION
PUM.Optional.DisableMRT, HKLM\SOFTWARE\POLICIES\MICROSOFT\MRT|DONTREPORTINFECTIONINFORMATION**

Registry Data: 0
(No malicious items detected)

Data Stream: 0
(No malicious items detected)

Folder: 0
(No malicious items detected)

File: 0
(No malicious items detected)

Physical Sector: 0
(No malicious items detected)

WMI: 0
(No malicious items detected)

**Comment by TotalChaos05** [comment]
dont run it as admin and you should be fine
